openapi: '3.0.1'
info:
  title: 'Devices API Documentation'
  description: 'API for managing devices and their associated details'
tags:
  - name: Devices
paths:
  /api/devices:
    get:
      summary: Get all devices
      tags:
        - Devices
      responses:
        '200':
          description: List of all devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
    post:
      summary: Create a new device
      tags:
        - Devices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hbl_id:
                  type: string
                  description: HBL ID of the device
                ip:
                  type: string
                  description: IP address of the device
                mask:
                  type: string
                  description: Subnet mask of the device
                dns:
                  type: string
                  description: DNS of the device
                last_connection:
                  type: string
                  format: date-time
                  description: Last connection time of the device
                mode:
                  type: string
                  description: Operating mode of the device
      responses:
        '200':
          description: Device created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the operation
                  message:
                    type: string
                    description: Message describing the outcome
                  device:
                    type: object
        '400':
          description: Required field(s) missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '409':
          description: Device with the same HBL ID already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
  /api/devices/byhbl_id/{hbl_id}:
    get:
      summary: Get a device by HBL ID
      tags:
        - Devices
      parameters:
        - name: hbl_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device details
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
  /api/devices/{uid}:
    get:
      summary: Get a device by UID
      tags:
        - Devices
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device details
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
    put:
      summary: Update a device
      tags:
        - Devices
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hbl_id:
                  type: string
                  description: HBL ID of the device
                ip:
                  type: string
                  description: IP address of the device
                mask:
                  type: string
                  description: Subnet mask of the device
                dns:
                  type: string
                  description: DNS of the device
                last_connection:
                  type: string
                  format: date-time
                  description: Last connection time of the device
                mode:
                  type: string
                  description: Operating mode of the device
      responses:
        '200':
          description: Device updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the operation
                  message:
                    type: string
                    description: Message describing the outcome
                  device:
                    type: object
        '400':
          description: Required field(s) missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
    delete:
      summary: Delete a device
      tags:
        - Devices
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device deleted successfully
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
